ANCHO_GRILLA = 11  # NO EDITAR
LARGO_GRILLA = 16  # NO EDITAR

# Complete con los demás parámetros
CANTIDAD_VIDAS = 3
TIEMPO_CUENTA_REGRESIVA = 15
MULTIPLICADOR_PUNTAJE = 1.5
MIN_CARACTERES = 3
MAX_CARACTERES = 10
MIN_VELOCIDAD = 0.9
MAX_VELOCIDAD = 1.1

# Cantidad constructor
MAXIMO_FANTASMAS_VERTICAL = 2
MAXIMO_FANTASMAS_HORIZONTAL = 3
MAXIMO_PARED = 4
MAXIMO_ROCA = 2
MAXIMO_FUEGO = 1
